FROM python:3.7

RUN pip install fastapi uvicorn httpx pillow jinja2 python-multipart
EXPOSE 80
RUN mkdir -p /etc/fastapi/app
COPY Calculate/ /etc/fastapi/app
WORKDIR /etc/fastapi/app
CMD ["uvicorn", "main_1:app", "--host", "0.0.0.0", "--port", "80"]
# CMD ["uvicorn", "main_2:app", "--host", "0.0.0.0", "--port", "80"]