FROM python:3.7

RUN pip install fastapi uvicorn httpx pillow sqlalchemy jinja2 python-multipart
EXPOSE 80
RUN mkdir -p /etc/fastapi/app
COPY DB/ /etc/fastapi/app
WORKDIR /etc/fastapi/app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]